name: Users
description: Users module
version: 0.4
dependsOn:
  - auth
seeds: true
seedsWeight: 0
routes:
  - { uri: /users, method: resource, model: User, uses: UserController }
admin:
  enabled: true

roles:
  -
    name: admin
    display_name: Administrator
    description: Site administrator

  -
    name: editor
    display_name: Editor
    description: Editor

permissions:
  -
    name: access-administration
    display_name: Access Administration
    description: Allow access to site administration
    roles: [admin, editor]
