name: Messages
description: Messaging, contact messages
version: 0.2
seeds: true
routes:
  - { uri: contact-messages, method: resource, uses: ContactMessageController }
contactMessageEmailTo:
  - admin@example.org
