name: Messages
description: Messaging, contact messages
version: 0.1
seeds: true
paths:
  migrations: Database
  factories: Database
  seeds: Database
  controllers:
routes:
  -
    uri: contacts
    method: resource
    uses: ContactMessagesController
